#!/bin/sh

dir=`dirname $0`

if [ "$1" = "-g" ]
then
    $dir/gradlew :cli:shadowJar
fi

if [ -z "$JAVA" ]
then
    JAVA=java
    if [ -n "$JAVA_HOME" ]
    then
        JAVA="$JAVA_HOME/bin/java"
    fi
fi

$JAVA -ea -jar "modules/cli/build/libs/DIVE-Application-0.1-SNAPSHOT-all.jar" "$@"
