#!/bin/sh

dir=`dirname $0`

# No spaces in file names!
#cp=`echo "$dir/lib/* $dir/modules/core/bin $dir/modules/cli/bin" | tr ' ' ':'`
cp="$dir/lib/*:$dir/modules/core/bin:$dir/modules/cli/bin:$dir/modules/dafny/bin"

java -ea -classpath $cp edu.kit.iti.algover.cli.Main "$@"
