package edu.kit.iti.algover.theoremprover;

import edu.kit.iti.algover.term.DefaultTermVisitor;
import edu.kit.iti.algover.term.Term;

/**
 * Class that handles the translation of open PVCs to KeY Proof obligations, in order to use them in KeY
 * Created by sarah on 6/3/16.
 */
public class KeYTrans{



    public KeYTrans(){
        createFileHeader();
        //create problembody

    }

    private StringBuilder createFileHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("//This is an autogenerated Proof file by AlgoVer");
        sb.append("//The following PVC has to be shown: +pvc.genName+method.genName");
        //create declarations

        return sb;
    }

    private StringBuilder createVarDecl(){
        StringBuilder sb = new StringBuilder();
        sb.append("\\programVariables{\n");
        sb.append("}");
        return sb;
    }

}
/*\programVariables {
  int i, j;
}

\problem {
        \<{
            i = 1;
            j = 3;
            i = 2;
          }\> i = 2
}*/

